[bar.default]
capsule = true
capsule_opacity = 0.75
capsule_radius = 2
margin_ends = 0
margin_edge = 0
radius = 0
padding = 15
scale = 1.0
thickness = 35
start = [ "clock", "group:g2", "media" ]
center = [ "group:g3" ]
end = [ "control-center", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "tray" ]

[[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "temp" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "cpu", "temp", "ram" ]
    opacity = 0.5
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    border = "primary"
    id = "g3"
    members = [ "active_window", "workspaces" ]
    opacity = 0.0
    padding = 6.0

[dock]
auto_hide = true
background_opacity = 1
enabled = true
icon_size = 32
launcher_icon = "noctalia"
launcher_position = "start"
magnification = false
pinned = [ "brave-origin", "anki", "org.kde.kdenlive", "kitty" ]
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 360

    [idle.behavior.suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600

[shell]
avatar_path = "/home/pranjal/.face"
polkit_agent = true
settings_show_advanced = false
telemetry_enabled = false
font_family = "FiraCode Nerd Font"
password_style = "random"
ui_scale = 1

    [shell.screenshot]
    directory = "/home/pranjal/Pictures/Screenshots"

[location]
auto_locate = true

[theme]
builtin = "Catppuccin"
wallpaper_scheme = "Catppuccin"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "kitty", "kcolorscheme", "mango", "niri" ]
enable_community_templates = false

[wallpaper]
directory = "/home/pranjal/Pictures/walls"
transition_on_startup = true

[widget.active_window]
display = "icon_only"
icon_size = 22.0
min_length = 0.0

[widget.workspaces]
minimal = true
scale = 1.25

[widget.bluetooth]
show_label = true

[widget.media]
title_scroll = "always"
hide_when_no_media = true

[widget.network]
show_label = false

[widget.cpu]
show_label = false

[widget.ram]
show_label = false

[widget.temp]
show_label = false

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Calendar"
    type = "google"


[desktop_widgets]
widget_order = [ "desktop-widget-watermark" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-watermark]
    box_height = 64.0
    box_width = 288.0
    cx = 1264.0
    cy = 896.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-watermark.settings]
        background = false
        description = "Go to Settings to Activate Archlinux"
        title = "Activate Archlinux"