source = colors.conf
$font = JetBrains Mono


animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

# INPUT FIELD
input-field {
    size = 20%, 5%
    outline_thickness = 5
    inner_color = $primary_container
    outer_color = $primary
    check_color = $tertiary
    fail_color = rgb(255, 115, 115)
    font_color = $on_primary_container
    fade_on_empty = false
    rounding = 10
    font_family = $font
    placeholder_text =<span> Enter Password 󰌾 </span>
    fail_text = $PAMFAIL
    dots_spacing = 0.25
    position = 0, -20
    halign = center
    valign = center
}

# USER IMAGE
image {
    monitor =
    path = /home/$USER/.face
    size = 150
    rounding = 10 # no rounding
    position = 0, 200
    halign = center
    valign = center
}

# USERNAME
label {
    monitor =
    text = <b>$USER</b>
    font_size = 20
    font_family = $font
    color = $primary
    position = 0, 90
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME 
    font_size = 90
    font_family = $font
    color = $on_secondary_container
    position = -40, -10
    halign = right
    valign = top
}

# BATTERY
label {
    monitor =
    text = cmd[update:5000] upower -b | grep percentage | awk '{print "󰂂 BAT: "$2}'
    font_size = 20
    font_family = $font
    color = $on_secondary_container
    position = 20, 20
    halign = left
    valign = bottom
}

shape {
    monitor =
    size = 400,150
    color = $secondary_container
    rounding = 10
    border_size = 10
    border_color = $primary

    position =  -10, -10
    halign = right
    valign = top
}