monitor=,preferred,auto,1.5


# Variables
$terminal = alacritty
$fileManager = thunar
$menu = rofi -show drun

source = hyprland/rules.conf
source = hyprland/prefs.conf
source = hyprland/input.conf
source = hyprland/theme.conf
source = hyprland/env.conf
source = hyprland/exec.conf
source = hyprland/animation.conf
source = hyprland/keybind.conf
source = hyprland/layouts.conf
