color0 #584142
color1 #ffb4ab
color2 #ffb3b5
color3 #ffb3b5
color4 #ffb868
color5 #ffb3b5
color6 #ffb3b5
color7 #f4dddd
color8 #a68a8a
color9 #ffb4ab
color10 #ffb3b5
color11 #ffb3b5
color12 #ffb868
color13 #ffb3b5
color14 #ffb3b5
color15 #f4dddd

cursor                #f4dddd
cursor_text_color     #1c1011
background            #1c1011
foreground            #f4dddd
selection_foreground  #dfbfbf
selection_background  #584142
active_border_color   #ffb3b5
inactive_border_color #584142
url_color             #ffb3b5

active_tab_foreground   #680019
active_tab_background   #ffb3b5
inactive_tab_foreground #dfbfbf
inactive_tab_background #584142
cursor_trail_color      #dfbfbf
