# EXEC

exec-once = /usr/lib/xdg-desktop-portal 
exec-once = /usr/lib/xdg-desktop-portal-gtk 
exec-once = /usr/lib/xdg-desktop-portal-hyprland 
exec-once = systemctl --user start hyprpolkitagent 
exec-once = sh -c Scripts/wallchange.sh
exec-once = hypridle 
exec-once = waybar --config $HOME/.config/waybar/config-hypr.jsonc
exec-once = kdeconnectd