shell /usr/bin/fish

font_family Firacode Nerd Font
font_size 12
window_padding_width 10
cursor_shape_unfocused block

map ctrl+shift+p load_config_file

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
