shell /usr/bin/fish

font_family Cascadia Code NF
font_size 14
window_padding_width 8
cursor_shape_unfocused block

map ctrl+shift+p load_config_file

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
