[config]
mode = "dark"
caching = true

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.mango]
input_path = '~/.config/matugen/templates/mango.conf'
output_path = '~/.config/mango/colors.conf'
index = -1
post_hook = 'mmsg -d reload_config' 

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunst'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.Obsidian]
input_path = '~/.config/matugen/templates/obsidian.json'
output_path = '~/Documents/hyphen/.obsidian/snippets/matugen.css'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.heroic]
input_path = '~/.config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/themes/matugen.css'
