
# Monitors

monitorrule=name:eDP-1,scale:1.5

# Environment Variables

env=QT_QPA_PLATFORMTHEME,qt6ct


# Exec
exec-once = /usr/lib/xdg-desktop-portal
exec-once = /usr/lib/xdg-desktop-portal-gtk 
exec-once = /usr/lib/xdg-desktop-portal-wlr 
exec-once = waybar-local
exec-once = brightnessctl s 30%
exec-once = kdeconnectd
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = sh -c $HOME/Scripts/wallchange.sh
exec-once = wl-clip-persist --clipboard regular
exec-once = hypridle 
exec-once = wlsunset -s 18:00 -S 7:00

# Misc

drag_tile_to_tile=1
no_border_when_single=0
allow_tearing=2

# Animations

animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=fade
layer_animation_type_open=zoom
layer_animation_type_close=fade

# Blur

blur=1
blur_optimized=1

# Opacity

focused_opacity = 0.95
unfocused_opacity = 1

# Appearence

gappih=5
gappiv=5
gappoh=5
gappov=5
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=4
cursor_size=24
cursor_theme=breeze_cursors
source=~/.config/mango/colors.conf


#--------Layout--------------
# MASTER

default_mfact=0.5

# SCROLLER

scroller_default_proportion=0.75
scroller_ignore_proportion_single=0
scroller_focus_center=1


#-------- Rules--------------

tagrule=id:1,layout_name:scroller
tagrule=id:3,layout_name:tgmix
windowrule=width:600,height:400,appid:matugen_color_pick,isfloating:1,isglobal:1
windowrule=width:600,height:400,appid:folder_color,isfloating:1,isglobal:1
windowrule=force_tearing:1,appid:steam_app_default
windowrule=focused_opacity:1,appid:firefox


#--------INPUT--------------

trackpad_natural_scrolling=1
tap_to_click=1
drag_lock=0
middle_button_emulation=1
tap_and_drag=1

# -------KEYBINDS-----------

bind=super+shift,r,reload_config
bind=super+shift,x,quit

# Layouts

bind=SUPER,s,setlayout,scroller
bind=SUPER,t,setlayout,tile
bind=SUPER,bracketleft,scroller_stack,left
bind=SUPER,bracketright,scroller_stack,right

# Scratchpad

bind=SUPER,i,minimized
bind=SUPER,z,toggle_scratchpad
bind=SUPER+SHIFT,i,restore_minimized


# Switch to tag

bind=super,1,view,1
bind=super,2,view,2
bind=super,3,view,3
bind=super,4,view,4
bind=super,5,view,5
#bind=super,6,view,6
#bind=super,7,view,7
#bind=super,8,view,8
#bind=super,9,view,9

# Move window to tag

bind=super+shift,1,tag,1
bind=super+shift,2,tag,2
bind=super+shift,3,tag,3
bind=super+shift,4,tag,4
bind=super+shift,5,tag,5
#bind=super+shift,6,tag,6
#bind=super+shift,7,tag,7
#bind=super+shift,8,tag,8
#bind=super+shift,9,tag,9


# Application Binding

bind=super,w,spawn,firefox
bind=super,e,spawn,thunar
bind=super,l,spawn,hyprlock
bind=super,return,spawn,alacritty
bind=super,r,spawn_shell,pkill rofi || rofi -show drun
bind=super+shift,s,spawn_shell,slurp | grim -g - - | wl-copy
bind=super,a,spawn_shell,sleep 1 && $HOME/Scripts/wallchange.sh # Sleep is required for the script to work properly

bind=super,q,killclient
bind=super,f,togglefullscreen
bind=super+shift,f,togglefakefullscreen
bind=super,p,togglefloating
bind=super+shift,p,toggle_all_floating

bind=super,left,focusdir,left
bind=super,right,focusdir,right
bind=super,up,focusdir,up
bind=super,down,focusdir,down

bind=super+shift,Up,resizewin,+0,-50
bind=super+shift,Down,resizewin,+0,+50
bind=super+shift,Left,resizewin,-50,+0
bind=super+shift,Right,resizewin,+50,+0

# ===== Brightness =====
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set 10%+
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 10%- --min-value=4800

# ===== Volume =====
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER+shift,btn_left,moveresize,curresize
mousebind=NONE,btn_middle,togglemaximizescreen,0

# ===== Gesture =====
gesturebind=none,right,3,viewtoleft
gesturebind=none,left,3,viewtoright

