# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x1c1011ff
bordercolor = 0xa68a8aff
dropcolor = 0xffb3b580
splitcolor = 0xffb868ff
focuscolor = 0xffb3b5ff
maximizescreencolor = 0xffb3b5ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xffb868ff
globalcolor = 0xee626fff
overlaycolor = 0x72373bff
